### PR TITLE
updated test folder with new boilerplate

### PR DESCRIPTION
**Pull request by Syd-Vigilant**
Updated test folder with new boilerplate dir, verify_boilerplate.py and make.sh files.

### CODE REVIEW

**Comment by Syd-Vigilant** [comment]
Test this please

**Comment by venkayya** [comment]
test this please

**Comment by Syd-Vigilant** [comment]
Test this please

**Review by chrislovecnm — APPROVED** [review]

**Comment by chrislovecnm** [comment]
We need to track these failures and figure out these flakes

**Comment by Syd-Vigilant** [comment]
Test it again

**Comment by chrislovecnm** [comment]
test this please

**Comment by chrislovecnm** [comment]
test this please

**Comment by raddaoui** [comment]
ok to test

**Pull request merged**
